<?php

if (!defined('ABSPATH')) {
    exit;
}

return [
    'id' => 'universally_settings',
    'title' => 'Universally',
    'logoPath' => '/assets/logo-full-dark.svg',
    'headerActions' => [
        [
            'icon' => 'dashicons-admin-site',
            'label' => __('Dashboard', 'universally-language-translation-multilingual-tool'),
            'href' => 'https://app.universally.com/',
        ],
        [
            'icon' => 'dashicons-book',
            'label' => __('Docs', 'universally-language-translation-multilingual-tool'),
            'href' => 'https://universally.com/docs/',
        ],
    ],
    'menu' => [
        'location' => 'toplevel',
        'icon' => 'dashicons-admin-generic',
        'iconPath' => '/assets/menu-icon.svg',
    ],
    'schema' => [
        [
            'type' => 'tab',
            'id' => 'general_tab',
            'label' => __('General', 'universally-language-translation-multilingual-tool'),
        ],
        [
            'type' => 'section',
            'id' => 'api_section',
            'label' => __('API', 'universally-language-translation-multilingual-tool'),
            'showSave' => false,
        ],
        [
            'id' => 'api_key',
            'type' => 'api-key',
            'endpoint' => 'universally/v1/validate-api-key',
            'label' => __('API Key', 'universally-language-translation-multilingual-tool'),
            'description' => __('Enter your API key to receive updates and support. The API key can be found in the app under the [Api Settings](https://app.universally.com/) section.', 'universally-language-translation-multilingual-tool'),
            'placeholder' => __('64-character API key', 'universally-language-translation-multilingual-tool'),
            'validate' => 'regex:/^[a-fA-F0-9]{64}$/',
            'sanitize' => 'trim|text_field',
        ],
        [
            'type' => 'section',
            'id' => 'languages_list_section',
            'label' => __('Languages', 'universally-language-translation-multilingual-tool'),
            'showSave' => false,
        ],
        [
            'id' => 'languages',
            'type' => 'languages-table',
            'label' => '',
            'endpoint' => 'universally/v1/languages',
        ],
        [
            'type' => 'tab',
            'id' => 'language_switcher_tab',
            'label' => __('Language Switcher', 'universally-language-translation-multilingual-tool'),
        ],
        [
            'type' => 'section',
            'id' => 'language_switcher_section',
            'label' => __('Language Switcher', 'universally-language-translation-multilingual-tool'),
        ],
        [
            'id' => 'implementation',
            'type' => 'cards',
            'label' => __('Implementation', 'universally-language-translation-multilingual-tool'),
            'description' => __('Select how do you want to implement the language switcher on site.', 'universally-language-translation-multilingual-tool'),
            'sanitize' => 'key',
            'columns' => 2,
            'options' => [
                'auto' => [
                    'label' => __('Auto', 'universally-language-translation-multilingual-tool'),
                    'description' => __('Automatically insert in the page without any code needed', 'universally-language-translation-multilingual-tool'),
                ],
                'custom' => [
                    'label' => __('Custom', 'universally-language-translation-multilingual-tool'),
                    'description' => __('Use a shortcode to insert the language switcher in your theme', 'universally-language-translation-multilingual-tool'),
                ],
            ],
            'max' => 1,
            'default' => 'auto',
        ],
        [
            'id' => 'position',
            'type' => 'select',
            'label' => __('Position', 'universally-language-translation-multilingual-tool'),
            'description' => __('Choose where to automatically insert the language switcher. This will only be used if you select the **Auto** {implementation} option.', 'universally-language-translation-multilingual-tool'),
            'options' => [
                'bottom_right' => __('Bottom Right', 'universally-language-translation-multilingual-tool'),
                'bottom_left' => __('Bottom Left', 'universally-language-translation-multilingual-tool'),
                'top_right' => __('Top Right', 'universally-language-translation-multilingual-tool'),
                'top_left' => __('Top Left', 'universally-language-translation-multilingual-tool'),
            ],
            'default' => 'bottom_right',
            'sanitize' => 'key',
            'conditions' => [
                'implementation = auto',
            ],
        ],
        [
            'id' => 'language_switcher_shortcode',
            'type' => 'copyable',
            'label' => __('Shortcode', 'universally-language-translation-multilingual-tool'),
            'description' => __('Use this shortcode to insert the language switcher in a custom place.', 'universally-language-translation-multilingual-tool'),
            'content' => '[universally_switcher]',
            'buttonText' => __('Copy Code', 'universally-language-translation-multilingual-tool'),
            'separator' => false,
            'conditions' => [
                'implementation = custom',
            ],
        ],
        [
            'id' => 'language_switcher_php_code',
            'type' => 'copyable',
            'label' => __('PHP Code', 'universally-language-translation-multilingual-tool'),
            'description' => __('Use this PHP code to insert the language switcher in a custom place.', 'universally-language-translation-multilingual-tool'),
            'content' => "if (function_exists('universally_switcher')) {\n   universally_switcher();\n}\n",
            'buttonText' => __('Copy Code', 'universally-language-translation-multilingual-tool'),
            'separator' => false,
            'conditions' => [
                'implementation = custom',
            ],
        ],
        [
            'id' => 'show_language_names',
            'type' => 'toggle',
            'label' => __('Language Names', 'universally-language-translation-multilingual-tool'),
            'inlineLabel' => __('Display the language names', 'universally-language-translation-multilingual-tool'),
            'default' => true,
            'sanitize' => 'bool',
            'separator' => false,
        ],
        [
            'id' => 'show_country_flags',
            'type' => 'toggle',
            'label' => __('Country Flags', 'universally-language-translation-multilingual-tool'),
            'inlineLabel' => __('Display the country flags', 'universally-language-translation-multilingual-tool'),
            'default' => true,
            'sanitize' => 'bool',
            'separator' => false,
        ],
        [
            'id' => 'flag_style',
            'type' => 'select',
            'label' => __('Flag Style', 'universally-language-translation-multilingual-tool'),
            'description' => __('Choose the style of the country flags.', 'universally-language-translation-multilingual-tool'),
            'options' => [
                'rounded' => __('Rounded', 'universally-language-translation-multilingual-tool'),
                'square' => __('Square', 'universally-language-translation-multilingual-tool'),
            ],
            'conditions' => [
                'show_country_flags = true',
            ],
            'default' => 'rounded',
            'sanitize' => 'key',
        ],
        [
            'type' => 'tab',
            'id' => 'styling_tab',
            'label' => __('Styling', 'universally-language-translation-multilingual-tool'),
        ],
        [
            'type' => 'section',
            'id' => 'trigger_styling_section',
            'label' => __('Trigger Styling', 'universally-language-translation-multilingual-tool'),
        ],
        [
            'id' => 'trigger_bg',
            'type' => 'color',
            'label' => __('Background', 'universally-language-translation-multilingual-tool'),
            'sanitize' => 'trim|text_field',
            'separator' => false,
            'palette' => 'background',
        ],
        [
            'id' => 'trigger_text',
            'type' => 'color',
            'label' => __('Text Color', 'universally-language-translation-multilingual-tool'),
            'sanitize' => 'trim|text_field',
            'separator' => false,
            'palette' => 'text',
        ],
        [
            'id' => 'trigger_border',
            'type' => 'color',
            'label' => __('Border Color', 'universally-language-translation-multilingual-tool'),
            'sanitize' => 'trim|text_field',
            'separator' => false,
            'palette' => 'border',
        ],
        [
            'id' => 'trigger_border_hover',
            'type' => 'color',
            'label' => __('Border Hover', 'universally-language-translation-multilingual-tool'),
            'sanitize' => 'trim|text_field',
            'separator' => false,
            'palette' => 'border',
        ],
        [
            'id' => 'trigger_radius',
            'type' => 'range',
            'label' => __('Border Radius', 'universally-language-translation-multilingual-tool'),
            'min' => 0,
            'max' => 24,
            'step' => 1,
            'suffix' => 'px',
            'default' => 6,
            'sanitize' => 'trim|text_field',
        ],
        [
            'type' => 'section',
            'id' => 'dropdown_styling_section',
            'label' => __('Dropdown Styling', 'universally-language-translation-multilingual-tool'),
        ],
        [
            'id' => 'dropdown_bg',
            'type' => 'color',
            'label' => __('Background', 'universally-language-translation-multilingual-tool'),
            'sanitize' => 'trim|text_field',
            'separator' => false,
            'palette' => 'background',
        ],
        [
            'id' => 'dropdown_text',
            'type' => 'color',
            'label' => __('Text Color', 'universally-language-translation-multilingual-tool'),
            'sanitize' => 'trim|text_field',
            'separator' => false,
            'palette' => 'text',
        ],
        [
            'id' => 'dropdown_border',
            'type' => 'color',
            'label' => __('Border Color', 'universally-language-translation-multilingual-tool'),
            'sanitize' => 'trim|text_field',
            'separator' => false,
            'palette' => 'border',
        ],
        [
            'id' => 'dropdown_hover_bg',
            'type' => 'color',
            'label' => __('Item Hover Background', 'universally-language-translation-multilingual-tool'),
            'sanitize' => 'trim|text_field',
            'separator' => false,
            'palette' => 'background',
        ],
        [
            'id' => 'dropdown_radius',
            'type' => 'range',
            'label' => __('Border Radius', 'universally-language-translation-multilingual-tool'),
            'min' => 0,
            'max' => 24,
            'step' => 1,
            'suffix' => 'px',
            'default' => 6,
            'sanitize' => 'trim|text_field',
        ],
    ],
];