// Auto-generated by wppanel CLI. Do not edit manually.
import { registerField } from '../registry';

import { CardsField } from './field-cards/src';
import { CheckboxField } from './field-checkbox/src';
import { CheckboxesField } from './field-checkboxes/src';
import { ColorField } from './field-color/src';
import { CopyableField } from './field-copyable/src';
import { LanguagesTableField } from './field-languages-table/src';
import { ApiKeyField } from './field-api-key/src';
import { NumberField } from './field-number/src';
import { RadioField } from './field-radio/src';
import { RangeField } from './field-range/src';
import { SelectField } from './field-select/src';
import { TextField } from './field-text/src';
import { TextareaField } from './field-textarea/src';
import { ToggleField } from './field-toggle/src';

registerField('cards', CardsField);
registerField('checkbox', CheckboxField);
registerField('checkboxes', CheckboxesField);
registerField('color', ColorField);
registerField('copyable', CopyableField);
registerField('languages-table', LanguagesTableField);
registerField('api-key', ApiKeyField);
registerField('number', NumberField);
registerField('radio', RadioField);
registerField('range', RangeField);
registerField('select', SelectField);
registerField('text', TextField);
registerField('textarea', TextareaField);
registerField('toggle', ToggleField);
